# Generated by Django 5.2.1 on 2025-05-25 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='massege_type',
            new_name='message_type',
        ),
    ]
